baseurl = "http://roempoen.com"
title = "Roempoen"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "https://roempoen-com.disqus.com"

[params]
    author = "Seroempoen Mego"
    description = "John Doe's personal website"
    keywords = "blog,developer,personal"
    info = "An Amateur Coder and Coffeeholic"
#    avatarurl = "images/avatar.jpg"
#    footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Custom CSS
    custom_css = []

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/roempoen/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 2
    url = "https://gitlab.com/roempoen/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/roempoen/"
#[[params.social]]
#   name = "LinkedIn"
#   icon = "fab fa-linkedin"
#   weight = 4
#   url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@roempoen"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
#[[menu.main]]
#    name = "Projects"
#    weight = 3
#    url = "/projects/"
#[[menu.main]]
#    name = "Contact me"
#    weight = 5
#    url = "/contact/"

